# Generated by Django 2.2.9 on 2020-08-09 13:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Files',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('hsds_num', models.IntegerField()),
                ('category', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('file_name', models.CharField(max_length=100)),
                ('db_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Genes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('sequence', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Hsds',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('genes_list', models.TextField()),
                ('lengths', models.TextField()),
                ('type', models.CharField(max_length=30)),
                ('pf_num', models.TextField()),
                ('description', models.TextField()),
                ('e_value', models.TextField()),
                ('ipr', models.TextField()),
                ('domain', models.TextField()),
                ('species', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.Files')),
            ],
        ),
    ]
