# Generated by Django 2.2.9 on 2020-08-20 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Faq',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50)),
                ('question', models.TextField()),
                ('answer', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='KEGG',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_one', models.TextField()),
                ('class_two', models.TextField()),
                ('ko_num', models.CharField(max_length=30)),
                ('description', models.TextField()),
                ('genes_list', models.TextField()),
                ('species', models.CharField(max_length=50)),
                ('hsd_original_name', models.TextField()),
                ('hsd_num', models.IntegerField()),
            ],
        ),
    ]
