# Generated by Django 2.2.9 on 2020-10-09 17:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0002_faq_kegg'),
    ]

    operations = [
        migrations.AddField(
            model_name='genes',
            name='species_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='database.Files'),
            preserve_default=False,
        ),
    ]
