# Generated by Django 2.2.9 on 2021-06-30 02:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0004_auto_20201010_0021'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hsds',
            name='e_value',
        ),
        migrations.CreateModel(
            name='Ncbi_ID',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('accession', models.CharField(max_length=100)),
                ('start', models.IntegerField()),
                ('stop', models.IntegerField()),
                ('strand', models.CharField(max_length=10)),
                ('length', models.IntegerField()),
                ('gene_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.Genes')),
                ('species_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.Files')),
            ],
        ),
    ]
