# Generated by Django 2.2.9 on 2020-10-09 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fileOperation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QandA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50)),
                ('question', models.TextField()),
                ('answer', models.TextField()),
            ],
        ),
    ]
